[package]
name = "gateway-api"
version = "0.4.0"
description = "Kubernetes Gateway API bindings in Rust"
authors = ["Shane Utt <shaneutt@linux.com>"]
license = "MIT"
keywords = ["kubernetes", "gateway-api"]
categories = ["api-bindings"]
homepage = "https://gateway-api.sigs.k8s.io/"
repository = "https://github.com/kube-rs/gateway-api-rs"
edition = "2021"

[dependencies]
kube = { version = "^0.87.1", default-features = false, features = ["derive"] }
k8s-openapi = { version = "0.19.0" }
schemars = "0.8.13"
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.106"
serde_yaml = "0.9.25"

[dev-dependencies]
anyhow = "1.0.75"
hyper = "0.14.27"
kube = { version = "^0.87.1" }
k8s-openapi = { version = "0.19.0" , features = ["v1_27"] }
tokio = { version = "1.32.0", features = ["macros"] }
tower = "0.4.13"
uuid = { version = "1.4.1", features = ["v4", "fast-rng"] }
